name: 'Update GAP package website'
description: 'Update the gh-pages branch of a GAP package'
inputs:
  version:
    description: 'the version of the package from which to update the website (if empty, use latest)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
      - name: "git -- checkout page"
        uses: actions/checkout@v4
        with:
          path: gh-pages
          ref: gh-pages

      - name: "website -- download asset to be deployed"
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: ${{ env.archive-file }}
      
      - name: "website -- extract the archive"
        run: |
          tar -xvf ${{ env.archive-file }}

      - name: "metadata -- copy metada to update page"
        run: |
          rm -r ./gh-pages/doc
          cp -r ${{ env.revision }}/doc/ ./gh-pages/doc/
          cp ${{ env.revision }}/PackageInfo.g ./gh-pages/PackageInfo.g
          cp ${{ env.revision }}/README.md ./gh-pages/README.md
          rm -v ./gh-pages/doc/.gitignore

      - name: "gap -- run update.g"
        working-directory: ./gh-pages
        run: |
          gap update.g

      - name: "git -- commit the update"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[${{ github.ref_name }}] - website update'
          repository: gh-pages
          branch: gh-pages
          push_options: '--force'
